regress: Fix edit-unittests
The test procedure tries to run the test from src/lib,
and it doesn't work very well with libtool...

make: Entering directory '/home/r1/r1/regress/build/src/lib'
/bin/rm -f edit.o
/usr/bin/g++ -DTEST_PROGRAM   -c -fno-strict-aliasing -fno-exceptions -fno-rtti  -I. -I..  -Wall -g -O0 -fno-strict-aliasing -fno-exceptions -fno-rtti  edit.c
/home/r1/r1/regress/build/libtool --silent --tag=CXX --mode=link /usr/bin/g++  -L. -o edit_test edit.o unittests.o  -lbac -lm -lpthread -ldl -ldl  -lssl -lcrypto
/home/r1/r1/regress/build/libtool --silent --tag=CXX --mode=install /usr/bin/install -c -m 0750 edit_test /home/r1/r1/regress/bin/
/bin/rm -f edit.o
/usr/bin/g++   -c -fno-strict-aliasing -fno-exceptions -fno-rtti  -I. -I..  -Wall -g -O0 -fno-strict-aliasing -fno-exceptions -fno-rtti  edit.c
make: Leaving directory '/home/r1/r1/regress/build/src/lib'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit statusn