Fix SQL query generated with ACLs
Issue reported by the console-acl-test

05-Aug 10:59 localhost-dir JobId 0: bdb.h:141 SELECT JobId,Media.VolumeName,FirstIndex,LastIndex FROM JobMedia JOIN Media
USING (MediaId)  JOIN Job USING (JobId)  JOIN Client USING (ClientId)  JOIN Pool USING (PoolId)  LEFT JOIN FileSet USING (
FileSetId)    WHERE  (Client.Name IN ('localhost-fd'))  ORDER BY JobMediaId ASC
05-Aug 10:59 localhost-dir JobId 0: Fatal error: bdb.h:141 bdb.h:141 query SELECT JobMediaId,JobId,Media.MediaId,Media.VolumeName,FirstIndex,LastIndex,StartFile,JobMedia.EndFile,StartBlock,JobMedia.EndBlock FROM JobMedia JOIN Media USING (MediaId)  JOIN Job USING (JobId)  JOIN Client USING (ClientId)  JOIN Pool USING (PoolId)  LEFT JOIN FileSet USING (FileSetId) WHERE  (Client.Name IN ('localhost-fd'))  ORDER BY JobMediaId ASC failed:
ERROR:  common column name "poolid" appears more than once in left table

The Pool restriction was introduced recently and is not mandatory.